version: '3'

volumes:
  mysql_db:

services:
  # Database
  wow_companion_mysql:
    image: mysql:8.0.28
    ports:
      - '7000:3306'
    volumes:
      - mysql_db:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: WoWCompanionRootPass2022
      MYSQL_DATABASE: myWoWCompanion_db
      MYSQL_USER: myWoWCompanion_user
      MYSQL_PASSWORD: MyWoWCompanionPass2022
    networks:
      - default
  # phpmyadmin
  wow_companion_phpmyadmin:
    depends_on:
      - wow_companion_mysql
    image: phpmyadmin/phpmyadmin:5.1.3
    ports:
      - '7100:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: WoWCompanionRootPass2022
    networks:
      - default