application:
  server:
    port: 7080
    url: http://localhost
  db-param:
    host: localhost
    port: 3306
    db-name: wow_companion_db
    user: wow_companion_user
    password: WoWCompanionPass2022
  api:
    blizzard:
      region: eu
      timeout: 1000

logging:
  level:
    fr.wowcompanion.server.tools:
      oauth2.BlizzardOAuth2FlowHandler: INFO
      api.blizzardapi.BlizzardApiInterceptor : INFO
    org:
      apache: INFO
      springframework:
        web: INFO
        security: INFO
        data: INFO

server:
  port : ${application.server.port}

spring:
  jpa:
    show-sql: false
    database-platform : org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  datasource:
    url: jdbc:mysql://${application.db-param.host}:${application.db-param.port}/${application.db-param.db-name}
    username: ${application.db-param.user}
    password: ${application.db-param.password}
    driverClassName: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          oauth-blizzard:
            client-id: 683474849cfe4dbfad419029326e0004
            client-secret: XuhqxDFNhqfu749ZNYKsEp7lj34epg32
            client-name: WoW Companion (DEV)
            provider: blizzard
            scope: wow.profile
            redirect-uri: "https://7080-jbwittner-wowcompanionse-7gg739u2wzn.ws-eu40.gitpod.io/login/oauth2/code/oauth-blizzard"
            client-authentication-method: basic
            authorization-grant-type: authorization_code 
        provider:
          blizzard:
            issuer-uri: https://${application.api.blizzard.region}.battle.net/oauth
            authorization-uri: https://${application.api.blizzard.region}.battle.net/oauth/authorize
            token-uri: https://${application.api.blizzard.region}.battle.net/oauth/token
            user-info-uri: https://${application.api.blizzard.region}.battle.net/oauth/userinfo
            user-name-attribute: battletag